#! /usr/bin/env bash

set -euo pipefail
shopt -s globstar

time=$(date +%d-%m-%Y_%H-%M-%S);
mkdir -p "converted-${time}";

for f in $1/**/*.mkv;
do
  relative=${f#$1/};
  filename=$(echo "${relative%.mkv}" | sed -e 's/\//--/g')

  ffmpeg -i "$f" -c copy "converted-${time}/${filename}.mp4";
done
